### ISSUE TITLE
Help Wanted: Handling Empty Keys in ParameterFile to Avoid Invalid YAML Errors

### ISSUE THREAD

**Issue by Ginga-Kennis** [ros2/launch_ros#437]
# **Help Wanted: Handling Empty Keys in ParameterFile to Avoid Invalid YAML Errors**

This issue seeks guidance on how to correctly handle empty keys in `launch_ros.parameter_descriptions.ParameterFile` when using `allow_substs=True`. When a substitution variable such as `$(var namespace)` is used as a YAML key and the corresponding substitution value is an empty string (`""`), it results in an invalid YAML structure, causing an error in the following example.

The issue arises because If `$(var namespace)` is replaced with an empty string, leaving only `:`, it violates YAML syntax and causes an error during launch.

## **Example**

Consider the following parameter file:

```yaml
$(var namespace):
  node_name:
    ros__parameters:
      message: "Hello, World!"
```

If `namespace="test_ns"` is provided at runtime, the substitution produces valid YAML:

```yaml
test_ns:
  node_name:
    ros__parameters:
      message: "Hello, World!"
```

However, if `namespace=""` (empty string) is passed, the result becomes:

```yaml
:
  node_name:
    ros__parameters:
      message: "Hello, World!"
```

This is **not valid YAML**, leading to a launch failure.

## **Request for Guidance**

I am looking for advice on the best way to handle this scenario:

- Should `ParameterFile` automatically remove empty keys instead of leaving only `:`?
- Is there a recommended workaround to prevent invalid YAML while still supporting variable substitution?

Any insights or best practices for handling this situation would be greatly appreciated.
